# Generated by Django 5.1.3 on 2024-11-14 10:07

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, verbose_name='აღწერა'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to='ingredients/', verbose_name='ფოტო'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='რაოდენობა'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('ml', 'milliliters'), ('piece', 'piece')], max_length=20, verbose_name='ერთეული'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menuapp.menucategory', verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dish_photos/', verbose_name='ფოტო'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ფასი'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menuapp.dish', verbose_name='ინგრედიენტები'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='სახელი'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/', verbose_name='კატეგორიის ფოტო'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menuapp.menucategory', verbose_name='მშობელი'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant', verbose_name='რესტორნები'),
        ),
    ]
