# Generated by Django 5.1.3 on 2024-11-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_ingredient_description_ingredient_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('გ', 'გრამი'), ('მლ', 'მილილიტრი'), ('ც', 'ცალი')], max_length=20, verbose_name='ერთეული'),
        ),
    ]
